### ISSUE TITLE
Explication Abdelkader

### ISSUE THREAD

**Issue by AbdelkaderA** [VBLab/repo_IoTski#14]
1- J'ai 'fork' le 'repo-IoTski' de virginie qui ce trouvé en partage public.
2- Je l'ai cloné en locale en passant par GitHub Desktop.
3-J'ai ouverts le fichier sur visual afin de le modifier.
4- Après les modifications effectuées, je l'ai comité et push a l'aide de GitHub Desktop.
5- J'ai ensuite créé un Pull requests pour envoyer mes modifications à Virginie afin qu'elle puisse les vérifier et les inclure dans le projet principal.
6-Virginie a reçu mes Pull request, elle les vérifie et les modifier s'il y a des conflits en choisissant ce qu'elle voulait garder.
7-Pour terminer elle approuve les Pull Request et les a clôtures.
Pull requests : Modif Abdel #5
Pull requests : modif 2 #7
@julienma

**Comment by julienma** [comment]
Ok pour moi @AbdelkaderA
