### ISSUE TITLE
Denis's front

### ISSUE THREAD

**Issue by ClementChal** [VBLab/repo_IoTski#4]
@AbdelkaderA J'aimerai une interface graphique à la Denis, est ce que c'est possible ?

**Comment by VBLab** [comment]
non non non et non....

**Comment by UlysC** [comment]
Oui cela me parait nécessaire @Clement-Chalencon

**Comment by VBLab** [comment]
ha mince une rébellion....on peut faire appelle à Denis sis vus vouez ?
